### ISSUE TITLE
when I press pdf button, this happens

### ISSUE THREAD

**Issue by AliEmn95** [fonol/anki-search-inside-add-card#109]
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-10 05:17:30

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 512, in _onBridgeCmd
  File "aqt\gui_hooks.py", line 2091, in __call__
  File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1781298089\src\command_parsing.py", line 166, in expanded_on_bridge_cmd
    notes.insert(0, SiacNote((-1, "PDF Meta", sp_body, "", "Meta", -1, "", "", "", "", -1)))
  File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1781298089\src\models.py", line 53, in __init__
    self.extract_start  : Optional[int] = props[11]
IndexError: tuple index out of range
![image](https://user-images.githubusercontent.com/63245416/84216405-ab341400-aade-11ea-80fe-cca150d6ca13.png)

**Comment by fonol** [comment]
Thanks for the report, I published a corrected version.

**Comment by succil** [comment]
same problem was occuring here, now it's working fine
