### ISSUE TITLE
Error when I try to retrieve old card's info

### ISSUE THREAD

**Issue by succil** [fonol/anki-search-inside-add-card#125]
I'm not sure if this error occurs because this card was create more than 400+ days ago or because I reseted its status last year, but whenever I click on Info I get this error message:

Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-16 21:09:00

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 512, in _onBridgeCmd
  File "aqt\gui_hooks.py", line 2091, in __call__
  File "C:\Users\succil\AppData\Roaming\Anki2\addons21\1781298089\src\command_parsing.py", line 119, in expanded_on_bridge_cmd
    set_stats(cmd[16:], calculateStats(cmd[16:], index.ui.gridView))
  File "C:\Users\succil\AppData\Roaming\Anki2\addons21\1781298089\src\stats.py", line 476, in calculateStats
    html = _buildTable(tables, reviewPlotData, ivlPlotData,
  File "C:\Users\succil\AppData\Roaming\Anki2\addons21\1781298089\src\stats.py", line 594, in _buildTable
    s += "<div style='text-align: center; width: 100%%;'><h3 style='margin-top: 10px;'>Reviews over time for <i>%s</i>:</h3>" % namesByCid[
KeyError: 1555302669286

**Comment by fonol** [comment]
Hi, I think I know where the problem is, but I have no computer for the next days, so I can't publish a fix sooner than next Monday.

**Comment by succil** [comment]
Working fine now
