### ISSUE TITLE
Last Update doesn't let anki to start the addon!

### ISSUE THREAD

**Issue by glitchlover** [fonol/anki-search-inside-add-card#133]
Here What anki says:
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Searching PDF Reading  Note-Taking in Add Dialog⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\Sohan computer\AppData\Roaming\Anki2\addons21\1781298089\__init__.py", line 4, in <module>
    from . import src
  File "C:\Users\Sohan computer\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 485, in <module>
    init_addon()
  File "C:\Users\Sohan computer\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 70, in init_addon
    state.db_file_existed = create_db_file_if_not_exists()
  File "C:\Users\Sohan computer\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 76, in create_db_file_if_not_exists
    conn = sqlite3.connect(file_path)
sqlite3.OperationalError: unable to open database fil
```

**Comment by fonol** [comment]
Hi, did you recently change the path to the db file ("siac-notes.db") in the addon config?
Does the file `siac-notes.db` exist on the path you have currently set at `addon note db folder path`? (If nothing is set there, the folder is the `user_files` folder in the add-on's folder.
It might be some process locking the database file. 
I guess restarting your computer didn't help?

**Comment by glitchlover** [comment]
I didn't touch any configuration
However though did not what happened I have reinstall the addon again turns out everything is fine
sorry for bothering bro
Thanks for the time.
