### ISSUE TITLE
Can't load queue with youtube video note

### ISSUE THREAD

**Issue by p4nix** [fonol/anki-search-inside-add-card#140]
Hello,

I recently introduced a youtube-video to my queue for testing reasons.
Now this error occurs when opening the queue or doing a search request which will return the video note:

```Debug info:
Anki 2.1.34 (8af8f565) Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-27 12:08:13
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 541, in _onBridgeCmd
  File "aqt/gui_hooks.py", line 2959, in __call__
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/command_parsing.py", line 584, in expanded_on_bridge_cmd
    index.ui.print_search_results(notes, stamp)
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/output.py", line 213, in print_search_results
    text                    = res.get_content()
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/models.py", line 85, in get_content
    return self._build_non_anki_note_html()
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/models.py", line 198, in _build_non_anki_note_html
    time = utility.text.get_yt_time_verbose(self.source)
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/utility/text.py", line 425, in get_yt_time_verbose
    time = get_yt_time(url)
  File "/Users/XYZ/Library/Application Support/Anki2/addons21/1781298089/src/utility/text.py", line 421, in get_yt_time
    return int(match.group(2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

While it will not crash the add-on completely, a lot of functions of the add-on don't work anymore after triggering this error, requiring a restart of Anki. It also appears if you try to load the video from the queue manager.

This happens to all video notes I try to add. Reproducing steps:
Create Note -> Title: StringICanSearchFor -> Source: https://www.youtube.com/watch?v=1XaJjbCSXT0 -> Create Note -> Search in database: StringICanSearchFor -> Error occurs.

**Comment by fonol** [comment]
Thanks for the report, fixed update is out.

**Comment by p4nix** [comment]
Fix works, thank you :)
