### ISSUE TITLE
PDF does not import. 

### ISSUE THREAD

**Issue by mumtazi** [fonol/anki-search-inside-add-card#144]
Hi!

I have recently updated the extension, and now whenever I try to import any pdf, it shows an error as such: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-15 11:08:04

Caught exception:
Traceback (most recent call last):
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-38>", line 2, in dropEvent
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 142, in webview_on_drop
    expanded_on_bridge_cmd(None, f"siac-create-note-source-prefill {url}", editor)
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\command_parsing.py", line 516, in expanded_on_bridge_cmd
    NoteEditor(self.parentWindow, add_only=False, read_note_id=None, tag_prefill = None, source_prefill=source)
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 147, in __init__
    self.setup_ui()
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 180, in setup_ui
    self.create_tab = CreateTab(self)
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 404, in __init__
    self.slider = QtPrioritySlider(self.parent.priority, self.parent.note_id, schedule=schedule)
  File "C:\Users\mumta\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\components.py", line 44, in __init__
    self.avg_prio           = round(get_avg_priority(), 1)
TypeError: type NoneType doesn't define __round__ method

Can you please let me know how I can import my PDFs?

Thank you.

**Comment by hoangpdang578** [comment]
I am facing same situation right now.!

**Comment by fonol** [comment]
thanks for the reports, patch is up!

**Comment by mumtazi** [comment]
Thank you! I admire your speed and efficiency!
