### ISSUE TITLE
Error after today's update(18 oct)

### ISSUE THREAD

**Issue by Andriymac** [fonol/anki-search-inside-add-card#145]
After updating to the last version when I open Anki an error pops out: 
<details>
<summary>Error log from anki</summary>

```
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-18 22:05:54
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩
Caught exception:
Traceback (most recent call last):
  File "/home/andrew/.local/share/Anki2/addons21/1781298089/src/index/indexing.py", line 99, in run
    self.t(*self.args)
  File "/home/andrew/.local/share/Anki2/addons21/1781298089/src/index/indexing.py", line 52, in _build_index
    index                               = FTSIndex(force_rebuild)
  File "/home/andrew/.local/share/Anki2/addons21/1781298089/src/index/fts_index.py", line 88, in __init__
    corpus = get_notes_in_collection()
  File "/home/andrew/.local/share/Anki2/addons21/1781298089/src/index/indexing_data.py", line 43, in get_notes_in_collection
    oList           = mw.col.db.all("select distinct notes.id, flds, tags, did, mid from notes left join cards on notes.id = cards.nid")
  File "anki/db.py", line 72, in all
  File "anki/db.py", line 33, in execute
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. 
The object was created in thread id 140627437446976 and this is thread id 140624420787968.
```
</details>

**Comment by fonol** [comment]
Huh, thanks for the report. I published an update which should fix the issue. You can test it by using "Rebuild Index" in the "Settings & Info" dropdown.

**Comment by Andriymac** [comment]
yeah, it works now. Thanks for a quick fix :+1:
