### ISSUE TITLE
create note error 

### ISSUE THREAD

**Issue by Bubblespu** [fonol/anki-search-inside-add-card#147]
I'm trying to add new pdf but this error message popped up. So, I can't add the pdf. 
Error 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-20 18:16:36

Caught exception:
Traceback (most recent call last):
  File "C:\Users\WIN10\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 208, in on_create_and_keep_open_clicked
    success = self._create_note()
  File "C:\Users\WIN10\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 253, in _create_note
    create_note(title, text, source, tags, None, specific_schedule, queue_schedule)
  File "C:\Users\WIN10\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 207, in create_note
    id      = conn.execute("""insert into notes (title, text, source, tags, nid, created, modified, reminder, lastscheduled, position, extract_start, extract_end, delay)
sqlite3.OperationalError: table notes has no column named extract_start

**Comment by fonol** [comment]
Hi, did you by chance recently use the add-on again after not using it for a longer time?

What would work is to
1. delete the `siac-notes.db` file (you can view the location under Settings & Info > Info > Path to Note DB
2. delete the add-on folder 
3. install the add-on again?

This would only be a good solution if you have no data to lose in the add-on (i.e. no add-on notes).
If not, I might have a solution with the next update, but that might take some more days.

**Comment by OcileCollection** [comment]
@Bubblespu Have you tried the new update? Did it solve the issue?
