### ISSUE TITLE
Error after add-on "Searching, PDF Reading & Note-Taking in Add Dialog" 

### ISSUE THREAD

**Issue by CurtisLe** [fonol/anki-search-inside-add-card#162]
I got a notice from Anki after adding:
**Error**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.

**Debug info:**
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-15 19:53:51

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 53, in handler
  File "aqt\main.py", line 142, in on_window_init
  File "aqt\main.py", line 190, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 231, in setupProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 2027, in __call__
  File "C:\Users\KHIEMLH\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 86, in <lambda>
    gui_hooks.profile_did_open.append(lambda : recalculate_priority_queue(True))
  File "C:\Users\KHIEMLH\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 300, in recalculate_priority_queue
    current             = _get_priority_list_with_last_prios()
  File "C:\Users\KHIEMLH\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 283, in _get_priority_list_with_last_prios
    res     = conn.execute(sql).fetchall()
sqlite3.OperationalError: no such column: delay

**Comment by fonol** [comment]
Thanks for the report, I uploaded a fixed version on Ankiweb.

**Comment by CurtisLe** [comment]
Thank you very much. Love you <3
