### ISSUE TITLE
Error when opening a newly created pdf file in the Queue Manager

### ISSUE THREAD

**Issue by TeEsTeBe** [fonol/anki-search-inside-add-card#164]
Steps to reproduce:
- create a new entry with Alt+N
- add a pdf with the "PDF" button
- set a title
- set priority to 20 using the "Priority and Schedule" slider
- click "Create" button
- double click on the item in the Queue Manager

Result:
```
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-16 17:48:43
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/queue_picker.py", line 1055, in cell_clicked
    self.display_note_modal(nid)
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/queue_picker.py", line 1076, in display_note_modal
    dialog = NoteEditor(self, id, add_only=True, read_note_id=None)
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 148, in __init__
    self.setup_ui()
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 186, in setup_ui
    self.metadata_tab = MetadataTab(self)
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 1040, in __init__
    self.setup_ui()
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 1051, in setup_ui
    self.author.setText(self.parent.note.author)
TypeError: setText(self, str): argument 1 has unexpected type 'float'
```

If I then restart Anki I get this:
```
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-16 17:48:43
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 53, in handler
  File "aqt/main.py", line 142, in on_window_init
  File "aqt/main.py", line 231, in setupProfile
  File "aqt/main.py", line 427, in loadProfile
  File "aqt/gui_hooks.py", line 2027, in __call__
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/index/indexing.py", line 40, in build_index
    state.index_data        = get_notes_in_collection()
  File "/home/schultetobrinke/.local/share/Anki2/addons21/1781298089/src/index/indexing_data.py", line 53, in get_notes_in_collection
    text = title + "\u001f" + text + "\u001f" + source + "\u001f" + (author if author else "")
TypeError: can only concatenate str (not "float") to str
```

I did a small experiment:
I deleted the .anki-siac-addon-data folder and changed the line which was mentioned in the first error message in the editor.py file from `self.author.setText(self.parent.note.author)` to `self.author.setText(str(self.parent.note.author))`. If I do the steps from the beginning the "Edit Note" window pops up (which is the expected behavior, I guess). If I switch to the tab "Metadata", the authors list shows "20.0".

I just installed the addon and haven't used it before. So the error occurs on a clean install with an empty database. The version should be the current one as I just installed the addon today. Deactivating all other addons also doesn't fix the problem.

**Comment by fonol** [comment]
Thanks for the report, might have caused that with my last update. An updated version is on Ankiweb. You'd have to delete the siac-notes.db file (or do a clean install) though.

**Comment by TeEsTeBe** [comment]
Wow, that was fast! The problem is gone, thank you!
