### ISSUE TITLE
add on error

### ISSUE THREAD

**Issue by dumbdreamed** [fonol/anki-search-inside-add-card#166]
hi.thanks for the recent updates.
with new update i get this error.
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-18 22:19:35

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 53, in handler
  File "aqt\main.py", line 142, in on_window_init
  File "aqt\main.py", line 190, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 231, in setupProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 2027, in __call__
  File "C:\Users\dreamed_dumb\AppData\Roaming\Anki2\addons21\1781298089\src\index\indexing.py", line 40, in build_index
    state.index_data        = get_notes_in_collection()
  File "C:\Users\dreamed_dumb\AppData\Roaming\Anki2\addons21\1781298089\src\index\indexing_data.py", line 53, in get_notes_in_collection
    text = title + "\u001f" + text + "\u001f" + source + "\u001f" + (author if author else "")
TypeError: can only concatenate str (not "float") to str

**Comment by fonol** [comment]
Hi, that error was already reported some days ago. For new users the fix is already there (just delete the old `siac-notes.db` file and restart) but that only is a solution if you don't have any add-on notes already, which you would lose. I'll include a general fix in the next update.

**Comment by fonol** [comment]
A possible fix is on Ankiweb.

**Comment by dumbdreamed** [comment]
really appreciate it man.thanks
