### ISSUE TITLE
Error on startup after latest update (running Anki 2.1.22)

### ISSUE THREAD

**Issue by MetalFir** [fonol/anki-search-inside-add-card#167]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨anki-search-inside-add-card-master⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 208, in loadAddons
  File "/Users/xxxx/Library/Application Support/Anki2/addons21/anki-search-inside-add-card-master/__init__.py", line 4, in <module>
    from . import src
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/anki-search-inside-add-card-master/src/__init__.py", line 557, in <module>
    init_addon()
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/anki-search-inside-add-card-master/src/__init__.py", line 82, in init_addon
    state.db_file_existed = create_db_file_if_not_exists()
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/anki-search-inside-add-card-master/src/notes.py", line 248, in create_db_file_if_not_exists
    conn.execute("""insert into notes_tmp (id, title, text, source, tags, nid, created, modified, reminder, lastscheduled, position, extract_start, extract_end, delay, author, priority, last_priority)
sqlite3.OperationalError: no such column: extract_start
⁩

**Comment by fonol** [comment]
Hi, have you not been using the add-on for a while by chance?
If you don't have add-on notes to lose yet, an easy fix would be to delete the `siac-notes.db` file.
Otherwise, I have done a possible fix (uploaded on Ankiweb and included in the newest release), which you might want to try out.
