### ISSUE TITLE
[Bug] sqlite syntax error

### ISSUE THREAD

**Issue by AM429** [fonol/anki-search-inside-add-card#171]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-29 01:21:55

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 541, in _onBridgeCmd
  File "aqt\gui_hooks.py", line 2959, in __call__
  File "C:\Users\polit\AppData\Roaming\Anki2\addons21\1781298089\src\command_parsing.py", line 578, in expanded_on_bridge_cmd
    index.ui.reading_modal.display(id)
  File "C:\Users\polit\AppData\Roaming\Anki2\addons21\1781298089\src\internals.py", line 54, in _check_ix
    return fn(*args, **kwargs)
  File "C:\Users\polit\AppData\Roaming\Anki2\addons21\1781298089\src\web\reading_modal.py", line 164, in display
    self._display_pdf(note.source.strip(), note_id)
  File "C:\Users\polit\AppData\Roaming\Anki2\addons21\1781298089\src\web\reading_modal.py", line 216, in _display_pdf
    extracts        = get_extracts(note_id, self.note.source)
  File "C:\Users\polit\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 692, in get_extracts
    res = c.execute(f"select extract_start, extract_end from notes where source = '{source}' and id != {nid} and extract_start >= 1").fetchall()
sqlite3.OperationalError: near "Reilly": syntax error
```
**Context :** This occurred while loading a pdf, Reilly is part of the pdf's name
**Simple Fix :**
```
res = c.execute(f"select extract_start, extract_end from notes where source = \"'{source}'\" and id != {nid} and extract_start >= 1").fetchall()
```

**Comment by fonol** [comment]
Hi, I guess the PDF's path has a single quote (') somewhere?
This was also reported by another user, it will be fixed with the next version :)

**Comment by AM429** [comment]
Actually yes, you are right
