### ISSUE TITLE
Deleting PDFs from Queue Manager raises error

### ISSUE THREAD

**Issue by tardiggerAde** [fonol/anki-search-inside-add-card#178]
**What I did**
- Imported a pdf into SIAC named Test
- Click SIAC -> Queue Manager
- Go to tab PDFs on the right side
- Select Test, click the Delete Note... button
- Click Yes on the confirmation message

**Error message:**
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.36 (c505894b) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-09 21:18:37
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/dialogs/queue_picker.py", line 1223, in del_btn_clicked
    run_hooks("user-note-deleted")
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/hooks.py", line 49, in run_hooks
    fn()
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/__init__.py", line 386, in <lambda>
    add_hook("user-note-deleted", lambda: get_index().ui.sidebar.refresh_tab(1))
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/web/sidebar.py", line 219, in refresh_tab
    self.refresh()
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/web/sidebar.py", line 222, in refresh
    self.display()
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/web/sidebar.py", line 157, in display
    self._editor.web.eval("""(() => {
AttributeError: 'NoneType' object has no attribute 'web'
```

**Additional Info:**
- After the error message is closed, Test is still displayed in the Queue manager. Closing and reopening the Queue manager shows that the PDF has been deleted successfully
- No error messages appear when deleting something from the Queue itself
- Launching Anki from the console, I received these additional messages (in addition to the Caught exception). They probably aren't relevant but I figured more info can't hurt :smile: 

_Before attempting to delete the note:_
```
add-on should use methods on col.decks, not col.decks.decks dict
add-on should use methods on col.decks, not col.decks.decks dict

Qt warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3051, resource id: 16004477, major code: 40 (TranslateCoords), minor code: 0`
```

_After the error message pops up_
```
Qt warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3260, resource id: 16005695, major code: 40 (TranslateCoords), minor code: 0 
Qt warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3604, resource id: 16002019, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by fonol** [comment]
Thanks for the detailed report, a fix is on Ankiweb.

**Comment by tardiggerAde** [comment]
Installed update, error has vanished completely along with Qt warning messages that appeared along with the error message. Thank you so much!
