### ISSUE TITLE
NameError: name 'tooltip' is not defined

### ISSUE THREAD

**Issue by oqicloud** [fonol/anki-search-inside-add-card#199]
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-14 12:39:55
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oqhan/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/importing/quick_web_import.py", line 223, in pdf
    tooltip("""You have to set a save path for imported URLs first.
NameError: name 'tooltip' is not defined

**Comment by fonol** [comment]
Thanks for the report, should be fixed.

**Comment by oqicloud** [comment]
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-14 12:39:55
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 464, in handler
  File "aqt/editor.py", line 451, in oncallback
  File "aqt/gui_hooks.py", line 1168, in __call__
  File "/Users/oqhan/Library/Application Support/Anki2/addons21/1781298089/src/web/reading_modal.py", line 348, in fill_sources
    if f in list(note.keys()):
AttributeError: 'NoneType' object has no attribute 'keys'

Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-14 12:39:55
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oqhan/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/importing/quick_web_import.py", line 208, in markdown
    mdtext.setPlainText(mdtext.toMarkdown())
AttributeError: 'QTextEdit' object has no attribute 'toMarkdown'

Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-14 12:39:55
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oqhan/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/editor.py", line 277, in on_create_and_keep_open_clicked
    self._reset()
  File "/Users/oqhan/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/editor.py", line 327, in _reset
    self.create_tab.text.setMarkdown("")
AttributeError: 'MDTextEdit' object has no attribute 'setMarkdown'

**Comment by fonol** [comment]
Update is up.

**Comment by oqicloud** [comment]
> 更新已完成。
Thank You！

Import unrecognized Chinese characters
![Uploading image.png…]()

**Comment by fonol** [comment]
In general, or only when you invoke the Create Note dialog from a specific place (e.g. Web import)?

**Comment by oqicloud** [comment]
> 通常，还是仅当您从特定位置调用“创建注释”对话框时（例如，Web导入）？

Yes. (e.g. Web import)

Double click on this point is also invalid, very good plug-in, but I am a novice still groping. Thanks again
