### ISSUE TITLE
Error after trying to open a note imported as markdown via menu 

### ISSUE THREAD

**Issue by samjohn24** [fonol/anki-search-inside-add-card#201]
Error after trying to open a note imported as markdown via menu : SIAC>Import>Web

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-22 00:20:00
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 515, in handler
  File "aqt/editor.py", line 484, in oncallback
  File "aqt/hooks_gen.py", line 1466, in __call__
  File "/home/scarbajali/.local/share/Anki2/addons21/1781298089/src/web/reading_modal.py", line 348, in fill_sources
    if f in list(note.keys()):
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by fonol** [comment]
Hi, thanks for the report.
I'll try to fix it in the next update!

**Comment by OcileCollection** [comment]
@samjohn24 Have you tried the new update? Did it solve the issue?
