### ISSUE TITLE
Error when loading the add-on

### ISSUE THREAD

**Issue by TheMystery28** [fonol/anki-search-inside-add-card#256]
With Anki 2.1.33

⁨Traceback (most recent call last):
File "aqt\addons.py", line 211, in loadAddons
File "C:\Users\X\AppData\Roaming\Anki2\addons21\1781298089\__init__.py", line 4, in <module>
from . import src
File "C:\Users\X\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 59, in <module>
from .menubar import Menu
File "C:\Users\X\AppData\Roaming\Anki2\addons21\1781298089\src\menubar.py", line 8, in <module>
from .dialogs.importing.quick_youtube_import import QuickYoutubeImport
ModuleNotFoundError: No module named '1781298089.src.dialogs.importing.quick_youtube_import'

**Comment by TheMystery28** [comment]
It's OK, I reinstall it.
