### ISSUE TITLE
Crash when trying to import yt video

### ISSUE THREAD

**Issue by klimekwiktor** [fonol/anki-search-inside-add-card#275]
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-31 14:46:31
Możliwy udział dodatków: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/wiktorklimek/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/importing/quick_youtube_import.py", line 98, in on_input
    data = json.loads(yt_videodata.text)
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fonol** [comment]
Hi, thanks for the report, I'll investigate.

**Comment by klimekwiktor** [comment]
Hi fonol, I tried to reproduce it once again now and it appears that was just the issue with publicity of the video I tried to embed. sorry for confusion

**Comment by fonol** [comment]
Okay, that's good to hear, thanks for the update.
