### ISSUE TITLE
editing note produces an error

### ISSUE THREAD

**Issue by amsaravi** [fonol/anki-search-inside-add-card#364]
**Describe the bug**

**To Reproduce**
open pdf file for editing whatever way you use will produce this error. works well with windows, but cant get it to work in linux manjaro

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.64 (581f82c5) Python 3.10.10 Qt 6.4.3 PyQt 6.4.2
Platform: Linux-4.19.279-2-MANJARO-x86_64-with-glibc2.37
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2023-06-19 08:56:28
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/queue_picker.py", line 1112, in cell_clicked
    self.display_note_modal(nid)
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/queue_picker.py", line 1139, in display_note_modal
    dialog = NoteEditor(self, id, add_only=True, read_note_id=None)
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 188, in __init__
    self.setup_ui()
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 224, in setup_ui
    self.create_tab     = CreateTab(self)
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/editor.py", line 601, in __init__
    self.slider = QtPrioritySlider(self.parent.priority, self.parent.note_id, show_spec_sched=False, show_similar=False)
  File "/home/mahdi/.local/share/Anki2/addons21/1781298089/src/dialogs/components.py", line 58, in __init__
    self.slider.setValue(prio_default)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'

**Comment by amsaravi** [comment]
This is the warnings when i bring the anki up from command line.

> Running with temporary Qt5 compatibility shims.
> Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
> Preparing to run...
> Qt info: 
> 
> GL Type: desktop
> Surface Type: OpenGL
> Surface Profile: CompatibilityProfile
> Surface Version: 4.6
> QSG RHI Backend: OpenGL
> Using Supported QSG Backend: yes
> Using Software Dynamic GL: no
> Using Multithreaded OpenGL: yes
> 
> Init Parameters:
>   *  application-name Anki 
>   *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
>   *  create-default-gl-context  
>   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>   *  disable-setuid-sandbox  
>   *  disable-speech-api  
>   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>   *  enable-threaded-compositing  
>   *  in-process-gpu  
>   *  use-gl desktop

**Comment by amsaravi** [comment]
using int() function will resolve the problems. maybe is python 3.10 issue

`self.slider.setValue(int(prio_default))`
