### ISSUE TITLE
23.10Qt6 Broken

### ISSUE THREAD

**Issue by DoctorToBeIn23** [fonol/anki-search-inside-add-card#375]
No add ons enabled except this one...

When I press "Notes" -> "+ New" I get the error every single time.
On a MacBook Pro.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.3.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-29 19:07:35
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 660, in _onBridgeCmd
  File "_aqt.hooks", line 5376, in __call__
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1781298089/src/command_parsing.py", line 345, in expanded_on_bridge_cmd
    elif handle_notes(self, cmd):
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1781298089/src/cmds/cmds_notes.py", line 22, in handle
    NoteEditor(editor.parentWindow)
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/editor.py", line 188, in __init__
    self.setup_ui()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/editor.py", line 224, in setup_ui
    self.create_tab     = CreateTab(self)
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1781298089/src/dialogs/editor.py", line 446, in __init__
    self.text.setFrameStyle(QFrame.StyledPanel | QFrame.Shadow.Sunken)
AttributeError: type object 'QFrame' has no attribute 'StyledPanel'

**Comment by Vilhelm-Ian** [comment]
@DoctorToBeIn23  

@OuraN2O this addon dosen't support Qt6 I made a fork that is Qt6 compatible if you want to check it out
https://github.com/Vilhelm-Ian/anki-search-inside-add-card

just do git clone https://github.com/Vilhelm-Ian/anki-search-inside-add-card
