### ISSUE TITLE
Bug when opening settings (Anki 23.10.1)

### ISSUE THREAD

**Issue by OuraN2O** [fonol/anki-search-inside-add-card#378]
**Bug**
Error message when opening settings of the addon (from the top bar SIAC -> Addon settings) 
The message : 
"Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-23 00:41:03
Greffons possiblement impliqués : ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\menubar.py", line 106, in settings
    dialog = SettingsDialog(mw.app.activeWindow())
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\settings.py", line 21, in __init__
    self.setup_ui()
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\settings.py", line 31, in setup_ui
    self.tab_shortcut     = ShortcutSettingsTab()
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\setting_tabs\shortcut.py", line 39, in __init__
    self.setup_ui()
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\setting_tabs\shortcut.py", line 127, in setup_ui
    item.manual_button.clicked.connect(ManualShortcut(self, item))
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\setting_tabs\shortcut.py", line 166, in __init__
    button_box = QDialogButtonBox(QDialogButtonBox.Ok|QDialogButtonBox.Cancel)
AttributeError: type object 'QDialogButtonBox' has no attribute 'Ok'"

Other error message when trying to add a new pdf (SIAC -> Import -> Create new)
The message : 
"Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-23 00:41:03
Greffons possiblement impliqués : ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\menubar.py", line 90, in import_create_new
    dialog = NoteEditor(mw.app.activeWindow(), prefill_with_opened_note = True)
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 188, in __init__
    self.setup_ui()
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 224, in setup_ui
    self.create_tab     = CreateTab(self)
  File "C:\Users\piszc\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 446, in __init__
    self.text.setFrameStyle(QFrame.StyledPanel | QFrame.Shadow.Sunken)
AttributeError: type object 'QFrame' has no attribute 'StyledPanel'"
**To Reproduce**
1. Go to SIAC (on the top bar)
2. Clic on addon settings (first error) or import then create new (second error)
3. Error message pops up

**Expected behavior**
I expect to be able to add new pdfs and see the settings of the addon

**Environment :**
 - OS: Windows 11
 - Anki version : 23.10.1

**Comment by Vilhelm-Ian** [comment]
@OuraN2O this addon dosen't support Qt6 I made a fork that is Qt6 compatible if you want to check it out
https://github.com/Vilhelm-Ian/anki-search-inside-add-card

just do ```git clone https://github.com/Vilhelm-Ian/anki-search-inside-add-card```
