### ISSUE TITLE
Bug - last update

### ISSUE THREAD

**Issue by Uitalo** [fonol/anki-search-inside-add-card#40]
When loading 'Searching PDF reading  note-taking in Add dialog':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/Users/cassiouitalo/Library/Application Support/Anki2/addons21/1781298089/__init__.py", line 4, in <module>
    from . import src
  File "/Users/cassiouitalo/Library/Application Support/Anki2/addons21/1781298089/src/__init__.py", line 322, in <module>
    initAddon()
  File "/Users/cassiouitalo/Library/Application Support/Anki2/addons21/1781298089/src/__init__.py", line 120, in initAddon
    aqt.editor._html += getScriptPlatformSpecific(config["addToResultAreaHeight"], delayWhileTyping)
  File "/Users/cassiouitalo/Library/Application Support/Anki2/addons21/1781298089/src/web/web.py", line 40, in getScriptPlatformSpecific
    script = f.read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46019: ordinal not in range(128)

**Comment by fonol** [comment]
SHit, I published an update, can you try it again?

**Comment by Uitalo** [comment]
now it's ok
