### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#82]
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-31 17:18:50

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 31, in cmd
  File "aqt\webview.py", line 97, in _onCmd
  File "aqt\webview.py", line 500, in _onBridgeCmd
  File "<D:\Anki\Anki.2.1.22\decorator.pyc:decorator-gen-110>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "D:\Anki\Anki.2.1.data\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "<D:\Anki\Anki.2.1.22\decorator.pyc:decorator-gen-60>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "D:\Anki\Anki.2.1.data\addons21\1781298089\__init__.py", line 194, in expanded_on_bridge
    hide_browser(self.web)
  File "D:\Anki\Anki.2.1.data\addons21\1781298089\__init__.py", line 141, in hide_browser
    addcards.form.deckArea.setMaximumWidth(3000)
AttributeError: 'QWidget' object has no attribute 'form'

**Comment by fonol** [comment]
Huh, that is weird. Can you please update again, and check if it is working?

**Comment by cjdduarte** [comment]
The button that generated the error is gone.
That's right?

![image](https://user-images.githubusercontent.com/42243532/78243982-1fd54b80-74bb-11ea-9c28-a320e9656616.png)

**Comment by fonol** [comment]
Yea. I uploaded the wrong add-on (https://ankiweb.net/shared/info/1783260740) by mistake.
